server:
  port: 6063


jasypt:
  encryptor:
    password: PSDCADMIN
    algorithm: PBEWithMD5AndDES


spring:
  application:
    name: psdc-apimgt
#  profiles: dev
  # 配置数据源
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:postgresql://182.10.2.118:5432/psdc_dev
    username: psdc
    password: ENC(4cDKgjxT/IgV60KehBlFrA==)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

# MyBatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.ct.psdc.**.**.mapper
  configuration:
    # 开启驼峰命名法
    map-underscore-to-camel-case: true
    use-generated-keys: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## 认证配置
security:
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://psdc-auth/oauth/user
      token-info-uri: http://psdc-auth/oauth/check_token
    client:
      client-id: psdc
      client-secret: 123456
      access-token-uri: http://psdc-auth/oauth/token
      grant-type: client_credentials,password
      scope: server